site_name: Central de Ajuda - OTMZI Solar
site_url: https://faqsolar.otmzi.com

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Configuração para o modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo        # Muda o topo amarelo para Azul
      accent: indigo        # Cor dos links e detalhes
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro

    # Configuração para o modo escuro (mantém o visual confortável à noite)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro

  features:
    - search.suggest
    - search.highlight
    - navigation.tabs      # Se seu menu crescer, ele cria abas bonitas no topo

nav:
  - 🏠 Início: index.md
  - 📠 Inversor e Monitoramento:
    - 🌐 Troquei de Roteador / Wi-Fi: inversor/wifi.md
    - 🟢 Significado das Luzes (LEDs): inversor/leds.md
  - 🧾 Fatura e Créditos:
    - 💰 Por que a conta não veio "Zero"?: fatura/conta-nao-zerou.md
    - 📊 Como entender os Créditos de Energia: fatura/creditos.md
  - 🧼 Manutenção e Cuidados:
    - 🧼 Como e quando limpar os painéis: manutencao/limpeza.md